In [2]:
import torch #импор библиотеки
#1.1 Создание тензоров
tensor0 = torch.rand(3,4) #Тензор размером 3x4, заполненный случайными числами от 0 до 1
print(tensor0)
tensor1= torch.zeros(2,3,4) #Тензор размером 2x3x4, заполненный нулями
print(tensor1)
tensor2 = torch.ones(5,5) # - Тензор размером 5x5, заполненный единицами
print(tensor2)
tensor3 = torch.arange(0, 16).reshape(4, 4) # - Тензор размером 4x4 с числами от 0 до 15 (используйте reshape)
print(tensor3)

tensor([[0.1180, 0.3031, 0.1884, 0.7039],
        [0.1534, 0.6679, 0.3787, 0.0367],
        [0.3303, 0.0605, 0.7723, 0.4829]])
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])


In [3]:
#1.2 Операции с тензорами 
a = torch.randint(0,16,(3,4))
b = torch.randint(0,10,(4,3))
t_a =a.t() #Транспонирование тензора A
print(t_a.shape)
a_matmuL_b = a@b # - Матричное умножение A и B
print(a_matmuL_b)
t_b = b.t()
element_multy = a * t_b # - Поэлементное умножение A и транспонированного B
print(element_multy)
sum_a = torch.sum(a) # - Вычисление суммы всех элементов тензора A
print(sum_a.item())

torch.Size([4, 3])
tensor([[134, 132,  90],
        [287, 200, 254],
        [307, 188, 262]])
tensor([[  0, 108,  21,   5],
        [ 11, 120,  45,  24],
        [112,  30, 112,   8]])
120


In [4]:
#1.3 Индексация и срезы
tensor5 = torch.arange(125).reshape(5, 5, 5)  #тензор размером 5x5x5
print(tensor5.shape)
first_rows = tensor5[:, 0, :] #Первая строка
print(first_rows)
last_columns = tensor5[:, :, -1] # - Последний столбец
print(last_columns)
matrix2x2 = tensor5[2:4, 2:4, 2:4] # - Подматрицa размером 2x2 из центра тензора
print(matrix2x2)
even_indices = tensor5[::2, ::2, ::2] #Все элементы с четными индексами
print(even_indices)

torch.Size([5, 5, 5])
tensor([[  0,   1,   2,   3,   4],
        [ 25,  26,  27,  28,  29],
        [ 50,  51,  52,  53,  54],
        [ 75,  76,  77,  78,  79],
        [100, 101, 102, 103, 104]])
tensor([[  4,   9,  14,  19,  24],
        [ 29,  34,  39,  44,  49],
        [ 54,  59,  64,  69,  74],
        [ 79,  84,  89,  94,  99],
        [104, 109, 114, 119, 124]])
tensor([[[62, 63],
         [67, 68]],

        [[87, 88],
         [92, 93]]])
tensor([[[  0,   2,   4],
         [ 10,  12,  14],
         [ 20,  22,  24]],

        [[ 50,  52,  54],
         [ 60,  62,  64],
         [ 70,  72,  74]],

        [[100, 102, 104],
         [110, 112, 114],
         [120, 122, 124]]])


In [ ]:
#1.4 Работа с формами
tensor6 = torch.arange(0,24) #тензор размером 24 элемента
print(tensor6.shape)
tenosr2x12= tensor6.reshape(2,12) # - 2x12
print(tenosr2x12.shape)
tensor3x8 = tensor6.reshape(3,8) # - 3x8
print(tensor3x8.shape)
tensor4x6 = tensor6.reshape(4,6)# - 4x6
print(tensor4x6.shape)
tensor2x3x4 = tensor6.reshape(2,3,4) # - 2x3x4
print(tensor2x3x4.shape)
tensor2x2x2x3 = tensor6.reshape(2,2,2,3) # - 2x2x2x3
print(tensor2x2x2x3.shape)