In [ ]:
import torch #импор библиотеки
#1.1 Создание тензоров
tensor0 = torch.rand(3,4) #Тензор размером 3x4, заполненный случайными числами от 0 до 1
print(tensor0)
tensor1= torch.zeros(2,3,4) #Тензор размером 2x3x4, заполненный нулями
print(tensor1)
tensor2 = torch.ones(5,5) # - Тензор размером 5x5, заполненный единицами
print(tensor2)
tensor3 = torch.arange(0, 16).reshape(4, 4) # - Тензор размером 4x4 с числами от 0 до 15 (используйте reshape)
print(tensor3)

tensor([[0.6831, 0.5899, 0.3021, 0.6671],
        [0.1175, 0.0086, 0.1131, 0.0976],
        [0.7677, 0.7643, 0.0407, 0.4118]])
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])
